server:
  port: 8080

--- #local
spring:
  profiles:
    active: local

rest:
  svr: localhost:8765

logging:
  level:
    root: debug

--- #prod
spring:
  profiles:
    active: prod

rest:
  svr: localhost:8080

logging:
  level:
    root: info
